/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CustomFieldListRelationFilter } from "../../customField/base/CustomFieldListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { TriggerListRelationFilter } from "../../trigger/base/TriggerListRelationFilter";

@InputType()
class ChatFlowWhereInput {
  @ApiProperty({
    required: false,
    type: () => CustomFieldListRelationFilter,
  })
  @ValidateNested()
  @Type(() => CustomFieldListRelationFilter)
  @IsOptional()
  @Field(() => CustomFieldListRelationFilter, {
    nullable: true,
  })
  customFields?: CustomFieldListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isActive?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TriggerListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TriggerListRelationFilter)
  @IsOptional()
  @Field(() => TriggerListRelationFilter, {
    nullable: true,
  })
  triggers?: TriggerListRelationFilter;
}

export { ChatFlowWhereInput as ChatFlowWhereInput };
